name: Devless Setup

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: typekpb/devless/.github/actions/devless-run@main
        with:
          aws_role_arn: ${{ secrets.AWS_ROLE_ARN }}
          api_gateway_url: ${{ secrets.DEVLESS_API_URL }}
          webhook_secret_param_name: /devless/webhook-secret
